# Generated by Django 3.1.7 on 2021-05-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='referee',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
    ]
