# Generated by Django 3.1.7 on 2021-05-19 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20210519_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='nick',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
