# Generated by Django 3.1.7 on 2021-05-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20210519_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nationality',
            new_name='CountryofBirth',
        ),
    ]
