# Generated by Django 3.1.7 on 2021-05-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20210519_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamHistory_Team',
        ),
    ]
