# Generated by Django 3.1.7 on 2021-05-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_delete_teamhistory_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sezon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loserteam', to='league.sezon'),
        ),
    ]
