# Generated by Django 3.1.7 on 2021-05-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_game_sezon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
    ]
