# Generated by Django 3.1.7 on 2021-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20210520_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ManyToManyField(to='league.Team'),
        ),
        migrations.DeleteModel(
            name='Team_Coach',
        ),
    ]
