# Generated by Django 3.1.7 on 2021-05-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20210521_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event_date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.FloatField(default=29.06),
        ),
    ]
