# Generated by Django 3.1.7 on 2021-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20210521_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.FloatField(default=20.0),
        ),
    ]
