# Generated by Django 3.1.7 on 2021-05-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_player_current_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_team', to='league.team'),
        ),
        migrations.AlterField(
            model_name='sezon',
            name='begin_date',
            field=models.DateField(verbose_name='data rozpoczecia'),
        ),
        migrations.AlterField(
            model_name='sezon',
            name='end_date',
            field=models.DateField(verbose_name='data zakonczenia'),
        ),
        migrations.AlterField(
            model_name='team',
            name='adc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adc', to='league.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.leagueclassification'),
        ),
        migrations.AlterField(
            model_name='team',
            name='jung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jung', to='league.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid', to='league.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='supp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supp', to='league.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='league.player'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='join_date',
            field=models.DateField(verbose_name='data rozpoczecia wspolpracy'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='leave_date',
            field=models.DateField(verbose_name='data zakonczenia wspolpracy'),
        ),
    ]
