# Generated by Django 3.1.7 on 2021-05-23 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_auto_20210522_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_Img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
