# Generated by Django 3.1.7 on 2021-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_auto_20210523_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_Img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
