# Generated by Django 3.1.7 on 2021-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_remove_leagueclassification_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ManyToManyField(to='league.Coach'),
        ),
    ]
